spring:
  application:
    name: example-manage
server:
  port: 8090
  
eureka:
  client:
    registry-fetch-interval-seconds: 20
  instance:
    lease-renewal-interval-in-seconds: 20
    lease-expiration-duration-in-seconds: 40
    
    prefer-ip-address: true
    hostname: ${spring.cloud.client.ipAddress}
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}

shiro:
  loginUrl: /manage/login
  doLoginUrl: /manage/doLogin
  successUrl: /manage/home
  successView: home
  logoutUrl: /manage/logout
  unauthorizedUrl: /manage/unauthorized
  unauthorizedView: unauthorized_view
  verificationCodeUrl: /manage/verificationCode
  verificationCodeHeight: 40
  verificationCodeWidth: 100
  filterChainDefinitions: /statc/**=anon,/manage/**=authc,resource,kickout
 
  redis:
    host: 127.0.0.1
    port: 6379
    password: root
    timeout: 10000
    expire: 1800