server:
  port: 8091
spring:
  application:
    name: example-server
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    master:
      url: jdbc:mysql://127.0.0.1:3306/cloud?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&allowMultiQueries=true
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver